version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      ## Run Test + Coverage
      - run:
          name: Run Test + Coverage
          command: yarn run ci:test

      ## Run Build
      - run:
          name: Build Gorg UI
          command: yarn run ci:build
