defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest-browsers

version: 2.1 # use CircleCI 2.1

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            # key template
            # embeds the current branch name using {{ .Branch }}
            # embeds "yarn.lock" into the key templace via {{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --ignore-engines

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn # cache path

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build-app:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Gorg UI
          command: yarn run ci:build
      # upload the build folder as an artifact
      - store_artifacts:
          path: public/
          destination: public
      - persist_to_workspace:
          root: .
          paths:
            - public

  # Installing and Running Selenium to Automate Browser Testing
  storyshots-puppeteer:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - persist_to_workspace:
          root: .
          paths:
            - test-reports

  snapshots:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - store_artifacts:
          path: test-reports/
          destination: test-reports
      - store_test_results:
          path: test-reports/
      - persist_to_workspace:
          root: .
          paths:
            - test-reports

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Test + Coverage
          command: yarn run ci:test
      - store_artifacts:
          path: coverage/
          destination: coverage
      - store_test_results:
          path: coverage/
      - store_test_results:
          path: src/__image_snapshots__/
      - persist_to_workspace:
          root: .
          paths:
            - coverage
            - test-reports

workflows:
  test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-app:
          requires:
            - build
      - snapshots:
          requires:
            - test
