defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest-browsers

version: 2.1 # use CircleCI version 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  dependencies: # runs not using Workflows must have a `build` job as entry point
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            # key template
            # embeds the current branch name using {{ .Branch }}
            # embeds "yarn.lock" into the key templace via {{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install --ignore-engines

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn # cache path

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build: # runs not using Workflows must have a `build` job as entry point
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Gorg UI
          command: yarn run ci:build
      # upload the build folder as an artifact
      - store_artifacts:
          path: public/
          destination: public

      - persist_to_workspace:
          root: .
          paths:
            - public

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mkdir junit-test-reports
      - run:
          name: Run Test + Coverage
          command: yarn run ci:test
      - store_test_results:
          path: src/__snapshots__/
      - persist_to_workspace:
          root: .
          paths:
            - coverage
            - junit-test-reports

  test-report:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - store_artifacts:
          path: junit-test-reports/
          destination: junit-test-reports
      - store_test_results:
          path: junit-test-reports/

  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - store_artifacts:
          path: coverage/
          destination: coverage
      - codecov/upload:
          file: coverage/coverage-final.json
          token: 9cfb46e1-c622-4ee2-a089-295bcb653ae0

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mkdir junit-lint-reports
      - run:
          name: Run Lint + Autofix
          command: yarn run ci:lint
      - persist_to_workspace:
          root: .
          paths:
            - junit-lint-reports

  lint-report:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - store_artifacts:
          path: junit-lint-reports/
          destination: junit-lint-reports
      - store_test_results:
          path: junit-lint-reports/

workflows:
  version: 2
  lint-test-build:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - lint-report:
          requires:
            - lint

      - test:
          requires:
            - dependencies
      - test-report:
          requires:
            - test
      - coverage:
          requires:
            - test

      - build:
          requires:
            - dependencies
            - lint
            - test
      # - deploy [TODO]
  # storyshots-puppeteer:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - run: mkdir junit-test-reports
  #     - run: yarn run ci:test:puppeteer
  #     # - run:
  #     #     name: Download Selenium
  #     #     command: |
  #     #       curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
  #     # - run:
  #     #     name: Start Selenium
  #     #     command: |
  #     #       java -jar selenium-server-standalone-3.5.3.jar -log junit-test-reports/selenium.log
  #     #     background: true
  #     - store_test_results:
  #         path: src/__image_snapshots__/
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - coverage
  #           - junit-test-reports
