version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/repo # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      - restore_cache: # special step to restore the dependency cache
          name: Restore Yarn Package Cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache: # special step to save the dependency cache
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: ## Run Test + Coverage
          name: Run Test + Coverage
          command: yarn run ci:test

      - run: ## Run Build
          name: Build Gorg UI
          command: yarn run ci:build
